In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [18]:
dataset = pd.read_csv('Iris.csv')

In [19]:
dataset.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [20]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
dataset.shape

(150, 6)

In [22]:
X = dataset.iloc[:,:4].values

In [23]:
X

array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       [  4. ,   4.6,   3.1,   1.5],
       [  5. ,   5. ,   3.6,   1.4],
       [  6. ,   5.4,   3.9,   1.7],
       [  7. ,   4.6,   3.4,   1.4],
       [  8. ,   5. ,   3.4,   1.5],
       [  9. ,   4.4,   2.9,   1.4],
       [ 10. ,   4.9,   3.1,   1.5],
       [ 11. ,   5.4,   3.7,   1.5],
       [ 12. ,   4.8,   3.4,   1.6],
       [ 13. ,   4.8,   3. ,   1.4],
       [ 14. ,   4.3,   3. ,   1.1],
       [ 15. ,   5.8,   4. ,   1.2],
       [ 16. ,   5.7,   4.4,   1.5],
       [ 17. ,   5.4,   3.9,   1.3],
       [ 18. ,   5.1,   3.5,   1.4],
       [ 19. ,   5.7,   3.8,   1.7],
       [ 20. ,   5.1,   3.8,   1.5],
       [ 21. ,   5.4,   3.4,   1.7],
       [ 22. ,   5.1,   3.7,   1.5],
       [ 23. ,   4.6,   3.6,   1. ],
       [ 24. ,   5.1,   3.3,   1.7],
       [ 25. ,   4.8,   3.4,   1.9],
       [ 26. ,   5. ,   3. ,   1.6],
       [ 27. ,   5. ,   3.4,   1.6],
 

In [24]:
y = dataset['Species'].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.39432836,  0.60275639,  0.55468293,  0.58680394],
       [-0.78237942, -0.85112836,  0.79325623, -1.22455228],
       [ 1.45462081,  0.72391345,  0.07753632,  1.039643  ],
       [ 1.13504935,  0.60275639, -0.87675689,  0.70001371],
       [-1.26173661, -0.12418599,  1.74754945, -1.11134251],
       [-1.21608354, -0.48765718,  0.79325623, -1.11134251],
       [-0.02910383,  0.60275639, -1.3539035 ,  0.70001371],
       [ 1.52310041,  1.08738463,  0.07753632,  1.09624788],
       [-1.07912435, -0.97228543,  0.79325623, -1.1679474 ],
       [-1.55848154, -0.48765718,  1.98612275, -1.11134251],
       [-0.75955288, -0.97228543,  1.03182954, -1.33776204],
       [-1.46717541, -1.09344249,  0.07753632, -1.22455228],
       [ 0.83830442,  0.84507051,  0.31610963,  0.81322347],
       [ 0.0622023 ,  1.2085417 , -0.63818359,  0.64340882],
       [ 1.63723308,  1.08738463, -0.16103698,  0.86982835],
       [-0.59976715, -1.45691367,  0.31610963, -1.28115716],
       [-0.0747569 ,  0.

In [27]:
X_test

array([[ 6.10039094e-01,  6.02756385e-01,  5.54682930e-01,
         1.32266741e+00],
       [-1.33021621e+00, -1.24185989e-01,  3.17898927e+00,
        -1.22455228e+00],
       [ 3.58947231e-01, -3.66500114e-01, -1.35390350e+00,
         1.90569769e-01],
       [-1.62696114e+00, -1.33575661e+00,  3.16109627e-01,
        -1.33776204e+00],
       [-6.22593687e-01, -8.51128363e-01,  1.74754945e+00,
        -1.16794740e+00],
       [ 1.29483508e+00,  1.93548407e+00, -6.38183586e-01,
         1.37927229e+00],
       [ 7.69824824e-01,  1.81432701e+00, -3.99610283e-01,
         1.49248205e+00],
       [ 6.78518692e-01,  6.02756385e-01, -3.99610283e-01,
         1.09624788e+00],
       [-3.25848758e-01, -7.29971301e-01, -8.76756889e-01,
         1.33964887e-01],
       [-1.30738968e+00, -4.87657176e-01,  1.98612275e+00,
        -1.33776204e+00],
       [-8.96512082e-01, -1.09344249e+00,  7.75363236e-02,
        -1.22455228e+00],
       [ 5.41559495e-01,  4.81599323e-01, -3.99610283e-01,
      

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [29]:
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor'], dtype='<U15')

In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 11]], dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))


Accuracy :  1.0


In [32]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0    Iris-virginica   Iris-virginica
1       Iris-setosa      Iris-setosa
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5    Iris-virginica   Iris-virginica
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11  Iris-versicolor  Iris-versicolor
12      Iris-setosa      Iris-setosa
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18   Iris-virginica   Iris-virginica
19   Iris-virginica   Iris-virginica
20   Iris-virginica   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26  Iris-versicolor  Iris-versicolor
27      Iris-setosa      Iris-setosa
28  Iris-versicolor  Iris-versicolor
29  Iris-versicolor  Iris-versicolor